# Generated by Django 4.2.15 on 2024-08-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bid_bid_placed_bid_bids_count_alter_bid_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='starting_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
